### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by pliang279** [wenhuchen/Variational-Vocabulary-Selection#1]
Thank you for open sourcing your code. Since this is an open-source project could you please add a license to the Github repository? Thanks!

**Comment by wenhuchen** [comment]
Hi Paul, thank you so much for your kind remind! I will add licenses to my open-source projects.

**Comment by pliang279** [comment]
Thanks! If it's not too much trouble could you add a license to this project? There are instructions here:

https://stackoverflow.com/questions/31639059/how-to-add-license-to-an-existing-github-project/37895659

Summary: "Create new file" -> "LICENSE" -> "Choose a license template"

**Comment by wenhuchen** [comment]
Hi, thanks a lot for the detailed instruction. I was actually searching for instructions for that in the morning since I'm not quite familiar with the legal stuff. I just added licenses to all my open source projects. Thank you so much and have a great day!
